session:
  mode: peer  # Mesh network

# Node definitions
nodes:

  # IMU sensor node
  # - type: nodes.imu_node.IMUNode
  #   params:
  #     robot_id: cash
  #     update_rate: 60.0  # Hz

  # Placeholder wrist/claw node (time-based arrival estimate only)
  - type: nodes.wrist_node.WristNode
    params:
      robot_id: cash
      update_rate: 30.0
      travel_speed: 1.0
