session:
  mode: peer  # Mesh network

# Node definitions
nodes:
  # Drivebase control node
  - type: nodes.drivetrain.DrivebaseNode
    params:
      robot_id: cash
  
  # IMU sensor node
  - type: nodes.imu_node.IMUNode
    params:
      robot_id: cash
      update_rate: 60.0  # Hz