session:
  mode: peer  # Mesh network

nodes:
  # Simple Teleop Node - PS5 controller to robot movement
  - type: nodes.teleop_node.TeleopNode
    params:
      robot_id: "cash"
      update_rate: 30.0  # Hz
      max_linear_speed: 3.0  # Maximum linear velocity (m/s)
      max_angular_speed: 2.0  # Maximum angular velocity (rad/s)
      deadzone: 0.05  # Controller deadzone

  # Robot Odometry Node - subscribes to velocity twists and IMU data
  - type: nodes.robot_odometry.RobotOdometryNode
    params:
      robot_id: "cash"
      update_rate: 30.0  # Hz

  # Rerun Visualization Node - subscribes to odometry/IMU and renders a 3D cube
  - type: nodes.rerun_viz.RerunVizNode
    params:
      robot_id: "cash"
      update_rate: 30.0  # Hz
      # Subscribe to Pose2D computed by the odometry node
      odom_topic: "/cash/state/pose2d"
      twist_topic: "/cash/state/twist"
      imu_quat_topic: "/cash/sensor/imu/quat"
      integrate_twist_if_needed: false
